create table address (
                         address_id bigint generated by default as identity,
                         address_type varchar(1) not null,
                         back_address varchar(200),
                         cell_phone varchar(25) not null,
                         front_address varchar(200) not null,
                         rcv_name varchar(50) not null,
                         zipcode varchar(20) not null,
                         primary key (address_id)
);

CREATE SEQUENCE IF NOT EXISTS seq_delivery_no MINVALUE 1 MAXVALUE 999999 CYCLE;
create table delivery (
                          delivery_id bigint generated by default as identity,
                          member_id varchar(20) not null,
                          created_date timestamp default CURRENT_TIMESTAMP,
                          created_id varchar(20) not null,
                          updated_date timestamp default CURRENT_TIMESTAMP,
                          updated_id varchar(50),
                          deliver_no varchar(14),
                          delivery_msg varchar(255),
                          delivery_status varchar(3) not null,
                          address_id bigint,
                          primary key (delivery_id)
);

create table member (
                        id bigint generated by default as identity,
                        auth_role varchar(10),
                        member_id varchar(255),
                        member_name varchar(255),
                        password varchar(255),
                        refresh_token varchar(300),
                        primary key (id)
);
alter table member
       add constraint uk01_member unique (member_id);